---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: minio
  namespace: longhorn
resources:
  - minio-auth-secret.yaml
  - minio-s3-secret.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
